# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions

name: 'Generate Block Colors'
description: 'Generate a color map for all blocks, based on the top texture.'
author: 'Mqxx'
branding:
  icon: 'droplet'
  color: 'purple'

inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to look for the resourcepack assets.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
