name: 'Test Action'

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test-action:
    name: 'Test Action'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v7
      
      - name: 'Generate assets to "./default_assets"'
        id: generate_assets
        uses: MinecraftPlayground/generate-assets@main
        with:
          version: 26.3
          path: './assets'
          parallel-downloads: 10
      
      - name: 'Test Action'
        id: test
        uses: './'
        with:
          path: './assets'

